### ISSUE TITLE
Cast/target range limitations.

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/AshenEmpires#10] opened 2022-09-04 22:00 UTC
The current spell range restrictions when we added party window target casting seem to override native casting within screenspace edges. Probably need to boost the allowed range a tiny bit for y-axis (increase by +1-2 tiles). X-axis appears fine based on feedback.

**Comment by davidjreese** [comment] 2022-09-05 01:38
I don't think the two are related. I am guessing this range restriction is something else. i read the code and don't see anyhing obvious. some spells are LOS, so some more data would be helpul.

1. what spell and where was target exactly.
2. same problem exist with ranged weapons?

**Comment by davidjreese** [comment] 2022-09-05 01:54
Dupe of: https://github.com/IronWillGames/AshenEmpires/issues/7

**Closed as completed by davidjreese** 2022-09-05 01:54 UTC
Labels: duplicate

**Comment by EJaynes** [comment] 2022-09-05 02:18
Ranged weapons work fine. Click to target works appropriately for regular attacks with ranged weapons or magic missile. It's just trying to cast spells at the top or bottom edge of screen that appear to be an issue. The feet have to be a full tile up from the bottom of the play area in order to allow casting, and the top of the window can be touchy as well currently on live environment.

**Comment by EJaynes** [comment] 2022-09-05 02:20
Superior heal on another player who is partially off-screen to the South of your character used to be an option. As long as you could see something to click on, you could heal that character. Now it will not heal unless that player is about two tiles north of that position where you can only see the top of the paperdoll character.
