### ISSUE TITLE
Login Screen Image Not Scaling

### ISSUE THREAD

**Issue by GM-Odran** [IronWillGames/AshenEmpires#35] opened 2022-09-07 20:28 UTC
![image](https://user-images.githubusercontent.com/112826917/188970750-effed197-0c14-4fdc-b04d-c6fb794f312d.png)

Display: 1920 x 1080
Game: 1024 x 768

**Comment by curxxx** [comment] 2022-09-07 20:34
duplicate of https://github.com/IronWillGames/AshenEmpires/issues/1

**Comment by Plutoooooooooooo** [comment] 2022-09-07 21:28
@IronWillGames can you please merge with #1

**Comment by davidjreese** [comment] 2022-09-07 23:55
Might have found this. Need someone who can repo it to test in STAGE

**Closed as completed** 2022-09-07 23:56 UTC
Labels: duplicate
