### ISSUE TITLE
Encounters are not respawning/recalculating in some areas.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/AshenEmpires#22] opened 2022-09-05 19:12 UTC
Someone mentioned that spawns of creatures must be completely eliminated before the encounter will refresh/respawn. 

Need more info on which spawns are exhibiting this behavior; a majority of spawns were retouched for Krog/Silvest/Whisperdale, so I might expect to see some issues in those locations, but shouldn't be system wide...can't think of what might have changed with encounters in last 3 months besides the restructuring for lowbie areas.

**Comment by EJaynes** [comment] 2022-09-05 22:04
Does the added corpse delay to NPC corpses also cause a slower respawn? Even empty NPC corpses remain for a bit longer than usual. Does the extended duration on empty player corpses also affect NPC corpses? Does the corpse cleanup have to occur before the new spawn can occur, causing this delay perhaps?

**Comment by curxxx** [comment] 2022-09-05 22:44
- SIlvest Minotaurs 
- Ryonkah's Crypt
- Darkbone Skeletons north of Samad
- Vrethpool Orc Fort
- Dalvon Mines

Have all been confirmed personally to be experiencing this. Mobs only spawn every few minutes and all at once simultaneously.

**Comment by curxxx** [comment] 2022-09-07 02:44
Frost Trolls east of Dunmarrow is also experiencing this

**Comment by marmotini** [comment] 2022-09-11 18:49
possibly related to the respawn issue: monster and player corpses, even when empty, disappear slower on A server compared to L/H, probably as designed since it makes it easier to resurrect people if they happened to not drop their bodies. The weird very slow monster respawn rate seems to only be happening on A, not on L/H. Tested at the silvest ant hill on A, the ants respawn really slowly. On L/H the ants respawn at the normal rate

**Comment by hgesler** [comment] 2022-09-12 17:27
Most likely config option emptydestroyinterval

**Comment by reikoshea** [comment] 2022-09-29 01:31
I saw this with blood liches in BLC (middle vertical hallway) on Legends

**Comment by curxxx** [comment] 2022-10-11 16:47
Related to server resource limits being hit? Sometimes notice a slight lag when mobs are about to respawn.

**Comment by davidjreese** [comment] 2022-10-30 00:06
I am putting up a new build on stage. I read through the code and think I see something that could cause spawns to 'pile up' as described in this ticket.

**Comment by davidjreese** [comment] 2022-10-30 16:47
@hgesler did some testing as well. think this is fixed now.

**Closed as completed by davidjreese** 2022-10-30 16:47 UTC
Labels: bug
